##' Run the Unit Tests
##'
##' Run the unit tests for the package and output with the given testthat reporter.
##' 
##  COMMENTED OUT @param reporter name of a testthat reporter. Defaults to \code{\link[testthat]{SummaryReporter}}.
##' 
##' @return Invisibly returns a data frame with the test results
##'
##' @author Claudia Beleites
##'
##' @seealso  \link[svUnit]{svUnit}
##' @keywords programming utilities
##' @export
##' @include unmixR-package.R
##' @importFrom testthat SummaryReporter ListReporter MultiReporter get_reporter with_reporter
##' 

unmixR.unittest <- function () {

    if (!requireNamespace("testthat", quietly=TRUE)) {
    warning("testthat required to run the unit tests.")
    return(NA)
  }
  
  tests <- eapply(env = getNamespace ("unmixR"), FUN = get.test, all.names=TRUE)
  tests <- tests [! sapply (tests, is.null)]
  
  reporter <- SummaryReporter$new()
  lister <- ListReporter$new()
  reporter <- MultiReporter$new(reporters = list(reporter, lister))

  with_reporter(reporter = reporter, start_end_reporter = TRUE, {
    for (t in seq_along(tests)){
      lister$start_file(names (tests [t]))
      tests [[t]] ()
    }
    get_reporter()$end_context()
  })


 invisible(lister$get_results())
}

##' test data for unit tests
##' @noRd
{
.C <- expand.grid ( 0 : 3, 0 : 3)
.C [, 3] <- 3 - rowSums (.C)
.C <- as.matrix (.C [.C [, 3] >= 0,])
dimnames(.C) <- list(samples = 1:10, wavelengths = paste("L", 1:3, sep = "")) # BH
.testdata <- data.frame (sample = paste("s", 1:10, sep = ""), x = I (.C))
rm (.C)
.correct <- c (1, 4, 10)

.correct.laser <- c (4, 79)

# Test data for volume change estimations
.points_2d <- rbind(
  # indices
  c(0, 0),
  c(3, 0),
  c(0, 4),
  # new_indices
  c(2, 2),
  c(5, 3),
  c(4, 10)
)
p <- ncol(.points_2d)+1
.correct_volume_changes <- matrix(NA_real_, nrow = nrow(.points_2d), ncol=p)
for(i in 1:nrow(.points_2d)) {
  for(j in 1:p) {
    inx <- 1:p
    inx[j] <- i
    .correct_volume_changes[i,j] <- simplex.volume(.points_2d, inx)
  }
}
rm(inx,p,i,j)

# Returns \code{n_points} internal points of a convhull generated by
# a given set of vertices. By default, coefficients for a vertex points range in [0,1].
# This can be changed by providing \code{max_coefficient} - vector of maximum coefficient
# for each of vertices.
.get_simplex_points <- function(vertices, max_coefficient=rep(1,nrow(vertices)), n_points=100) {
  p <- nrow(vertices)
  coefficients <- matrix(nrow=0, ncol = p)
  while (nrow(coefficients) < n_points) {
    coefficients <- rbind(
      coefficients,
      sapply(1:nrow(vertices), function(j) {
        runif(
          2*(n_points-nrow(coefficients)),
          max=max_coefficient[j])
      })
    )
    coefficients <- coefficients[rowSums(coefficients) < 1, ]
  }
  coefficients[1:n_points,] %*% vertices
}
}

##' get test that is attached to object as "test" attribute
##' @noRd
get.test <- function (object)
  attr (object, "test")

